### ISSUE TITLE
Kompatibilitaet mit anderen Templates

### ISSUE THREAD

**Issue by lisandi** [typo3-themes/theme_bootstrap_mosaic#14]
Ich habe heute die beiden Templates (Highland und Mosaic)<RTE Type Dropdown Mosaic.png><RTE Type Dropdown Highland.png> einmal ausprobiert und festgestellt dass im RTE die Type Layouts nicht kompatibel miteinander sind.

der eine zeigt Highland der andere Mosaic

Wenn die nicht kompatibel sind dann kann man die Templates nicht untereinander austauschen bzw. switchen 

In Highland sind Layout 1 = H1 -> Layout 5 = H5
In Highland sind Layout 1 = H3 und dann sehr unlogisch bis Layout 5 etc angeordnet.

Es scheint auch das h4 gleich zweimal vorkommt 
<img width="283" alt="screen shot 2015-09-10 at 11 32 13 pm" src="https://cloud.githubusercontent.com/assets/1982011/9794254/404110fc-5814-11e5-9b34-8ebb0428ce3f.png">
<img width="280" alt="screen shot 2015-09-10 at 11 32 32 pm" src="https://cloud.githubusercontent.com/assets/1982011/9794261/48d9934c-5814-11e5-8e04-0474fe057f9e.png">

ist das Absicht, oder einfach ein "bug" der Kompatibilitaet.

Ansonsten sehr gute Arbeit die ihr da geleistet habt.
<img width="170" alt="rte type dropdown highland" src="https://cloud.githubusercontent.com/assets/1982011/9794110/7f5af1fa-5813-11e5-83ef-7f513f96a80c.png">
<img width="202" alt="rte type dropdown mosaic" src="https://cloud.githubusercontent.com/assets/1982011/9794111/7fae62b8-5813-11e5-80cb-418461511ca6.png">

**Comment by kaystrobach** [comment]
duplicate von https://github.com/typo3-themes/theme_bootstrap_highland/issues/4 therefor this one is closed,so that we can discuss it at a central place

**Comment by Bunnyfield** [comment]
Actually this is the right place, since the result of the discussion is that if something has to be changed at all, then it has to be the way header layouts are handled by mosaic.

Rule of thumb is: Don't change the original list of values (0,1,2,3,4,5) and their labels unless you completely remove a value. Removed values will fall back to "default" then.

Any additional header layout must be added with another than the default set of values in TYPO3. i.e. you can add numeric values starting with 6 or even string values. So the developers of a Theme can decide if they want to keep the default set and add to it, or if they want to remove the default values, but they can not rename them.

**Comment by lisandi** [comment]
General Question concerning the headers. As an example I modified the headers in mosaic so that the h1-h5 settings will be reflected accordingly. http://t9.thaipo3.com/headers/
As there is the possibility to SORT Headers in that drop down list by giving them the right numbering it would be possible to keep at least all H1 H2 H3 etc settings together by using i.e.

i.e.

## Rename Layout-types

TCEFORM.tt_content.header_layout.altLabels {
    1 = H1 (primary font)
    2 = H2 (primary font)
    3 = H3 (primary font)
    4 = H4 (primary font)
    5 = H5 (primary font)
}
TCEFORM.tt_content.header_layout.addItems {
    6 = H2 Block Header (this should actually be moved than to 200 something like seen below)
    7 = H2 Block Header Row (dito)
    8 = Horizontal Line - No Header Text
    1000 = --- (only used as seperator here)
    1001 = H1 Title fadeInDown        (_)
    1002 = H1 Title fadeInUp             (_)
    1003 = H1 Title slideInLeft           (_)
    1004 = H1 Title slideInRight        (_)
    2000 = --- (only used as seperator here)
    2001 = H2 Block Header
    2002 = H2 Block Header Row
}

3 Questions came up:

Question 1:
While setting up this I added some more jquery animations to H1 in mosaic! (*) 
Our Editor here came up with the idea to make those animations separate and accessible just below the Header field. To have headers sliding in from the left and perhaps even having the text sliding in from the right would be a great animation which brings some kind of life into the sites. 

What would be the best way to provide a JQuery animation dropdown field just beside the Header field, so that those animations would be available for anykind of header? A lot of animated Header Types would be immediately accessible for editors and this list could be shorted for all those animation types. Beside this it would be compatible and usable in all templates.

Question 2:
What would you think would be the best kind of numbering those settings so that some kind of structures could be kept through out all templates. I started with 1001 for H1 - 2002 for H2 etc

Question 3:
To keep things understandable and always the same throughout all templates what would you suggest for Naming the H1 - H5 settings

like seen above (it is more understandable for editors but bigger effort to translate in other languages)

```
1 = H1 (primary font)
2 = H2 (primary font)
3 = H3 (primary font)
4 = H4 (primary font)
5 = H5 (primary font)
```

or the default (a bit confusing) in TYPO3 (Unfortunately the naming "Layout" gets used also at other places with other functionality! Translations already exist in many languages. Probably it would be a good idea to change that default generally in TYPO3 Core to another naming or change the naming where other so called "Layout" boxes appear.

```
1 = Layout 1
2 = Layout 2
3 = Layout 3
4 = Layout 4
5 = Layout 5
```

or

???

name any other idea to keep it best understandable also for Editors and not to much effort to translate in other languages. Thanks!

---

In General I think it could be quite easy be achieved to have lots of different Headers available and also Color Themes by simply combining all those different color schemes and header settings into one place. Template developers could add new color schemes and the could add new Header ideas and everything would be combinable and available in all templates.

This is actually a great benefit of TYPO3 thanks to TYPOscript in combination with using LESS

**Comment by kaystrobach** [comment]
@lisandi please open a PR, then we can discuss the PR directly in code ... no need to theoretical discussions, lets concentrate on real code ...

You can also do PRs without using git locally by just trying to edit a file on github ... each change can then be discussed and reviewed and so we see some progress and not only discussions ;)

chears Kay

**Comment by kaystrobach** [comment]
@lisandi regarding your animatejs stuff, i created an repo for that, if you want, you can use https://github.com/typo3-themes/themes_animatejs for publishing the code, this will enable you to use our buildinfrastructure for easy publishing, if you are interested, drop me a note and i will add you as a contributor to the repo
